---
title: "Activity 8 - Mini-competition"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(tidyverse)
library(tidyr)
```

```{r read data}
inventory <- read.csv("data/inventory.csv")
```

```{r explore data}
summary(inventory)

n_distinct(inventory$item_no)

inventory %>% 
  group_by(item_no) %>% 
  summarise(min = min(sold),
            q1 = quantile(sold, 0.25),
            median = median(sold),
            mean = mean(sold),
            q3 = quantile(sold, 0.75),
            max = max(sold)) %>% 
  arrange(mean)
```

```{r plot data}
inventory %>% 
  filter(item_no == "A510004") %>% 
  ggplot(aes(x = week, y = sold)) +
  geom_line() +
  theme_bw()


inventory %>% 
  filter(item_no == "154-2424B") %>% 
  ggplot(aes(x = week, y = sold)) +
  geom_line() +
  theme_bw() + 
  ggtitle("154-2424B Shipment History")
```

```{r inventory months}
inventory_month <- inventory %>% 
  mutate(month = ceiling(week/4))
```


```{r pivot inventory}
inventory_pivot <- inventory %>% 
           #if( week == 53) {"Current"} else{ paste("WeeksAway", 53 - week, sep = "") } ) %>% 
  mutate(weeks_away = paste("WeeksAway", 53 - week, sep = "")) %>% 
  select(item_no, weeks_away, sold) %>% 
  pivot_wider(names_from=weeks_away, values_from=sold)
```

```{r model inventory}
inventory_pivot_no_item <-inventory_pivot %>% 
  select(-item_no)
model<-glm(WeeksAway0 ~ ., data = inventory_pivot_no_item)
summary(model)
```

```{r pivot month}
inventory_month_pivot <- inventory_month %>% 
  mutate(months_away = paste("MonthsAway", month, sep = "")) %>%
  group_by(item_no, months_away) %>% 
  summarise(sold = sum(sold)) %>% 
  pivot_wider(names_from=months_away, values_from=sold)
```

```{r model my month}
model<-glm(MonthsAway0 ~ . -item_no, data = inventory_month_pivot)
summary(model)
```





```{r visualize and model by sum}
org_inventory <- inventory %>% 
  group_by(week) %>% 
  summarise(sold = sum(sold)) 

org_inventory %>% 
  ggplot(aes(x=week, y=sold)) +
  geom_line() +
  theme_bw()
```

```{r org pivot}
org_inventory_pivot <- org_inventory %>%   
  mutate(weeks_away = paste("WeeksAway", 53 - week, sep = "")) %>% 
  select(weeks_away, sold) %>% 
  pivot_wider(names_from=weeks_away, values_from=sold)
```

```{r org model}
glm(WeeksAway0~ ., data = org_inventory_pivot)
```

```{r item classes}
item_class <- inventory %>% group_by(item_no)

item_class <- item_class %>% mutate(item_class = nchar(item_no))
```

```{r item order frequency}
order_frequency <- inventory %>% 
  filter(sold > 0) %>% 
  group_by(item_no) %>% 
  summarise(count = n()) %>% 
  arrange(count)

order_frequency <- order_frequency %>% 
  mutate(is_frequent = count >= 12)
```

```{r join inventory month pivot and order frequency}
frequent_inventory_month_pivot <- list(inventory_month_pivot, order_frequency) %>% 
  reduce(full_join, by='item_no') %>% 
  filter(is_frequent)


model<-glm(MonthsAway0 ~ . -item_no -is_frequent -count, data = frequent_inventory_month_pivot, family = "poisson")
summary(model)

resid(model)
fitted.values(model)

ggplot(model, aes(x=resid(model), y=fitted.values(model))) +
  geom_point() + theme_bw() + ggtitle("Fitted vs Residuals")
```

